name: Run on workflows
on:
    schedule:
      - cron: "0 */6 * * *"
    push:
      branches: [ Newpatch ]
    workflow_dispatch:
    
env:
  APP_ID: "${{ secrets.APP_ID }}"
  API_HASH: "${{ secrets.API_HASH }}"
  OWNER: "${{ secrets.OWNER }}"
  BOT_TOKEN: "${{ secrets.BOT_TOKEN }}"
   


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v2
         with:
            ref: Newpatch
       - uses: styfle/cancel-workflow-action@0.9.0
         name: "Cancelling duplicate workflow runs"
         with:
            all_but_latest: true
            access_token: ${{ github.token }}
       - uses: actions/setup-node@v2
         with:
            node-version: '16'
       - name: Set up Python 3.9
         uses: actions/setup-python@v2.2.2
         with:
           python-version: 3.9
       - name: cloning repo and install

         continue-on-error: true
         run: |
           sudo apt -qq update && sudo apt -qq install -y --no-install-recommends ffmpeg neofetch
           pip3 install -r requirements.txt
          #  echo "APP_ID=${{ secrets.APP_ID }} | tee .env
          #  echo "API_HASH=${{ secrets.API_HASH }} | tee -a .env
          #  echo "OWNER={{ secrets.OWNER }} | tee -a .env
          #  
          #  echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }} | tee -a .env || echo "Proceeding with no bot"
          #  cat .env
       - name: Running
         timeout-minutes: 350
         continue-on-error: true
         run: |
           python3 -m bot
           echo "Bot Died"
